2021-05-17 22:29:44,396 INFO    MainThread:10807 [wandb_setup.py:_flush():69] setting env: {}
2021-05-17 22:29:44,396 INFO    MainThread:10807 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-17 22:29:44,396 INFO    MainThread:10807 [wandb_init.py:_log_setup():336] Logging user logs to /home/matthew/thesis/repo/master_thesis/wandb/run-20210517_222944-2es815oo/logs/debug.log
2021-05-17 22:29:44,396 INFO    MainThread:10807 [wandb_init.py:_log_setup():337] Logging internal logs to /home/matthew/thesis/repo/master_thesis/wandb/run-20210517_222944-2es815oo/logs/debug-internal.log
2021-05-17 22:29:44,397 INFO    MainThread:10807 [wandb_init.py:init():369] calling init triggers
2021-05-17 22:29:44,397 INFO    MainThread:10807 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 1000, 'seed_num': 24, 'torch_seed': 24, 'batch_size': 128, 'learning_rate': 0.001, 'dataset': 'DG15x15', 'architecture': 'MLP', 'total_fold': 3, 'Scheduler': 'Plateau'}
2021-05-17 22:29:44,397 INFO    MainThread:10807 [wandb_init.py:init():389] re-initializing run, found existing run on stack: h6vibdb1
2021-05-17 22:29:44,397 INFO    MainThread:10807 [wandb_run.py:finish():1167] finishing run fatalys/test/h6vibdb1
2021-05-17 22:29:44,397 INFO    MainThread:10807 [jupyter.py:save_history():320] not saving jupyter history
2021-05-17 22:29:44,397 INFO    MainThread:10807 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-17 22:29:44,397 INFO    MainThread:10807 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-17 22:29:44,397 INFO    MainThread:10807 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-05-17 22:29:44,398 INFO    MainThread:10807 [wandb_run.py:_restore():1466] restore
2021-05-17 22:29:44,613 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 818
  total_bytes: 818
}

2021-05-17 22:29:45,350 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 818
  total_bytes: 7002
}

2021-05-17 22:29:45,770 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7002
  total_bytes: 7002
}

2021-05-17 22:29:45,871 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7002
  total_bytes: 7002
}

2021-05-17 22:29:45,973 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7002
  total_bytes: 7002
}

2021-05-17 22:29:46,075 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7002
  total_bytes: 7002
}

2021-05-17 22:29:46,177 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7002
  total_bytes: 7002
}

2021-05-17 22:29:46,279 INFO    MainThread:10807 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7002
  total_bytes: 7002
}

2021-05-17 22:29:47,365 INFO    MainThread:10807 [wandb_run.py:_show_summary():1771] rendering summary
2021-05-17 22:29:47,366 INFO    MainThread:10807 [wandb_run.py:_show_history():1809] rendering history
2021-05-17 22:29:47,366 INFO    MainThread:10807 [wandb_run.py:_show_files():1838] logging synced files
2021-05-17 22:29:47,368 INFO    MainThread:10807 [wandb_init.py:init():418] starting backend
2021-05-17 22:29:47,368 INFO    MainThread:10807 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-17 22:29:47,370 INFO    MainThread:10807 [backend.py:ensure_launched():123] starting backend process...
2021-05-17 22:29:47,393 INFO    MainThread:10807 [backend.py:ensure_launched():127] started backend process with pid: 14735
2021-05-17 22:29:47,394 INFO    MainThread:10807 [wandb_init.py:init():423] backend started and connected
2021-05-17 22:29:47,396 INFO    MainThread:10807 [wandb_init.py:init():463] updated telemetry
2021-05-17 22:29:47,396 INFO    MainThread:10807 [wandb_init.py:init():482] communicating current version
2021-05-17 22:29:47,986 INFO    MainThread:10807 [wandb_init.py:init():487] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-17 22:29:47,987 INFO    MainThread:10807 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-05-17 22:29:48,246 INFO    MainThread:10807 [wandb_init.py:init():520] starting run threads in backend
2021-05-17 22:29:48,299 INFO    MainThread:10807 [wandb_run.py:_console_start():1524] atexit reg
2021-05-17 22:29:48,299 INFO    MainThread:10807 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-05-17 22:29:48,299 INFO    MainThread:10807 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-05-17 22:29:48,299 INFO    MainThread:10807 [wandb_run.py:_redirect():1438] Redirects installed.
2021-05-17 22:29:48,299 INFO    MainThread:10807 [wandb_init.py:init():544] run started, returning control to user process
2021-05-17 22:29:48,301 INFO    MainThread:10807 [wandb_run.py:_config_callback():749] config_cb None None {'train_size': 2666, 'test_size': 1334}
2021-05-17 22:29:48,303 INFO    MainThread:10807 [wandb_run.py:_config_callback():749] config_cb None None {'num_layers': 3, 'hidden_dim': 128}
2021-05-17 22:29:56,572 INFO    MainThread:10807 [wandb_run.py:finish():1167] finishing run fatalys/test/2es815oo
